#server:
#  port: 8080

spring:
  application:
    name: tamama
  datasource:
    url: jdbc:mariadb://localhost:3308/tamama?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: pw1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    defer-datasource-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  sql:
    init:
      mode: always
#  data:
#    redis:
#      port: 6379
#      host: 127.0.0.1
  batch:
    job:
      enabled: true
      name: job
    jdbc:
      initialize-schema: always # 운영 환경에서는 자동 생성되지 않도록 never로 많이 설정
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: info

redis:
  host: 127:0.0.1
  port: 6379
